server:
  port: 80
  address: 171.238.148.100
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "boulevard1"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 3
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""

logging:
  file:
    max-history: 1
    max-size: 3MB
  path: /app/logs/

  level:
    root: INFO
    lavalink: INFO
